import WeakSimplexConjectureLean

/-!
# Axiom audit

This file records the transitive axioms used by the principal public declarations. The accepted
output for every command is exactly `[propext, Classical.choice, Quot.sound]`.
-/

#print axioms WeakSimplex.measurableSet_lowerOrthant
#print axioms WeakSimplex.truncated_second_moment
#print axioms WeakSimplex.H_pos
#print axioms WeakSimplex.localLogMass_tendsto_atBot
#print axioms WeakSimplex.rankOne_inverse_bound
#print axioms WeakSimplex.exists_adaptivePotential_maximizer
#print axioms WeakSimplex.exists_adaptivePotential_maximizer_with_value
#print axioms WeakSimplex.Vendor.StatLean.AsymptoticStatistics.prekopaLeindler
#print axioms WeakSimplex.prekopa_leindler
#print axioms WeakSimplex.isLogConcave_gaussianQuadraticKernel
#print axioms WeakSimplex.measurable_isLogConcave_lintegral_right
#print axioms WeakSimplex.measurable_isLogConcave_convolution
#print axioms WeakSimplex.hasDerivAt_adaptivePotentialCoordinateLine
#print axioms WeakSimplex.adaptivePotential_stationary_coordinate
#print axioms WeakSimplex.adaptivePotential_compatibility
#print axioms WeakSimplex.adaptivePotential_value_identity
#print axioms WeakSimplex.exists_adaptiveWitnesses
#print axioms WeakSimplex.sq_matrixMul_apply_le_qform_of_isCorrelation
#print axioms WeakSimplex.exists_adaptiveWitnesses_of_weakSimplexCov
#print axioms
  WeakSimplex.Vendor.StatLean.ProbabilityTheory.multivariateGaussian_withDensity_exp_shift
#print axioms WeakSimplex.Vendor.StatLean.MeasureTheory.pi_withDensity_prod
#print axioms
  WeakSimplex.Vendor.StatLean.AsymptoticStatistics.Measure.withDensity_map_eq_map_withDensity
#print axioms WeakSimplex.multivariateGaussian_withDensity_exp_shift
#print axioms WeakSimplex.integral_exp_inner_sub_quadratic_mul
#print axioms WeakSimplex.isLogConcave_centeredTiltedHalfLine
#print axioms WeakSimplex.integral_mul_centeredTiltedHalfLine
#print axioms WeakSimplex.measurable_normalizedCenteredTiltedHalfLine
#print axioms WeakSimplex.normalizedCenteredTiltedHalfLine_nonneg
#print axioms WeakSimplex.integrable_normalizedCenteredTiltedHalfLine
#print axioms WeakSimplex.isBounded_range_normalizedCenteredTiltedHalfLine
#print axioms WeakSimplex.isLogConcave_normalizedCenteredTiltedHalfLine
#print axioms WeakSimplex.integral_normalizedCenteredTiltedHalfLine
#print axioms WeakSimplex.integral_mul_normalizedCenteredTiltedHalfLine
#print axioms WeakSimplex.normalizedCenteredTiltedHalfLine_product
#print axioms
  WeakSimplex.continuous_normalizedSelfConvolution_normalizedCenteredTiltedHalfLine
#print axioms WeakSimplex.AdaptiveWitnesses.preimage_adaptiveEndpoints_shift
#print axioms WeakSimplex.adaptiveProduct_mass_eq
#print axioms WeakSimplex.adaptiveValue_exp_bound
#print axioms WeakSimplex.lowerOrthant_eq_adaptiveProduct
#print axioms WeakSimplex.CenteredProductProperty
#print axioms WeakSimplex.lowerOrthant_ge_iid_of_posDef_of_centeredProduct
#print axioms WeakSimplex.Vendor.StatLean.AsymptoticStatistics.pi_gaussianReal_eq_withDensity
#print axioms WeakSimplex.Vendor.StatLean.AsymptoticStatistics.pi_gaussianReal_neg_invariant
#print axioms WeakSimplex.symmetricRectangle_ge_iid
#print axioms WeakSimplex.symmetricRectangle_gt_iid_of_ne_one
#print axioms WeakSimplex.symmetricRectangle_eq_iid_iff
#print axioms WeakSimplex.symmetricRectangle_ge_iid_of_posDef
#print axioms WeakSimplex.even_logConcave_product_of_posDef
#print axioms WeakSimplex.measurable_normalizedSelfConvolution
#print axioms WeakSimplex.normalizedSelfConvolution_nonneg
#print axioms WeakSimplex.isBounded_range_normalizedSelfConvolution
#print axioms WeakSimplex.isLogConcave_normalizedSelfConvolution
#print axioms WeakSimplex.normalizedSelfConvolution_law
#print axioms WeakSimplex.integral_normalizedSelfConvolution_eq_one
#print axioms WeakSimplex.integral_mul_normalizedSelfConvolution_eq_zero
#print axioms WeakSimplex.variance_id_normalizedSelfConvolution
#print axioms WeakSimplex.map_multivariateGaussian_sumDifference_eq_prod
#print axioms WeakSimplex.normalizedSelfConvolution_product_deficit_of_posDef
#print axioms WeakSimplex.integral_integral_sumDifferenceProduct_eq_sq
#print axioms WeakSimplex.centeredTiltedHalfLine_product_lt_of_ne_one
#print axioms WeakSimplex.measurable_iteratedNormalizedSelfConvolution
#print axioms WeakSimplex.iteratedNormalizedSelfConvolution_nonneg
#print axioms WeakSimplex.isBounded_range_iteratedNormalizedSelfConvolution
#print axioms WeakSimplex.isLogConcave_iteratedNormalizedSelfConvolution
#print axioms WeakSimplex.integral_iteratedNormalizedSelfConvolution_eq_one
#print axioms WeakSimplex.integral_mul_iteratedNormalizedSelfConvolution_eq_zero
#print axioms WeakSimplex.variance_id_iteratedNormalizedSelfConvolution
#print axioms WeakSimplex.isProbabilityMeasure_iteratedNormalizedSelfConvolution
#print axioms WeakSimplex.variance_id_withDensity_ofReal_pos
#print axioms WeakSimplex.hasLaw_iteratedNormalizedSelfConvolution_dyadicSum
#print axioms WeakSimplex.tendstoInDistribution_iteratedNormalizedSelfConvolution
#print axioms WeakSimplex.multivariateGaussian_eq_stdGaussian_withDensity
#print axioms WeakSimplex.exists_pos_le_gaussianDensityRatio_on_box
#print axioms WeakSimplex.mul_prod_setIntegral_le_integral_of_le_gaussianDensityRatio_on_box
#print axioms
  WeakSimplex.exists_eventual_pos_lower_bound_integral_iteratedNormalizedSelfConvolution
#print axioms WeakSimplex.centered_product_of_posDef
#print axioms WeakSimplex.centered_product_of_continuous
#print axioms WeakSimplex.lowerOrthant_ge_iid_of_posDef
#print axioms WeakSimplex.map_gaussianRegularization_eq_multivariateGaussian
#print axioms WeakSimplex.tendstoInDistribution_regularized_multivariateGaussian
#print axioms WeakSimplex.regularizedCovariance_posDef
#print axioms WeakSimplex.regularizedCovariance_isCorrelation
#print axioms WeakSimplex.regularizedCovariance_isWeakSimplexCov
#print axioms WeakSimplex.lowerOrthant_ge_iid
#print axioms WeakSimplex.multivariateGaussian_one_lowerOrthant
#print axioms WeakSimplex.lowerOrthant_gt_iid_of_ne_one
#print axioms WeakSimplex.lowerOrthant_eq_iid_iff
#print axioms WeakSimplex.coordinateMax
#print axioms WeakSimplex.continuous_coordinateMax
#print axioms WeakSimplex.coordinateMax_le_iff_mem_lowerOrthant
#print axioms WeakSimplex.coordinateMax_tail_le_iid
#print axioms WeakSimplex.gaussianMax_mgf_le_regularSimplex
#print axioms WeakSimplex.coordinateMax_tail_lt_iid_of_ne_one
#print axioms WeakSimplex.gaussianMax_mgf_lt_regularSimplex
#print axioms WeakSimplex.gaussianMax_mgf_eq_regularSimplex_iff
#print axioms WeakSimplex.regularSimplexGram
#print axioms WeakSimplex.gramNormalization
#print axioms WeakSimplex.gramNormalization_eq_one_iff
#print axioms WeakSimplex.gramMgf_normalization_identity
#print axioms WeakSimplex.gramGaussianMax_mgf_le_regularSimplex
#print axioms WeakSimplex.gramGaussianMax_mgf_lt_regularSimplex
#print axioms WeakSimplex.gramGaussianMax_mgf_eq_regularSimplex_iff
#print axioms WeakSimplex.codeGram
#print axioms WeakSimplex.codeGram_posSemidef
#print axioms WeakSimplex.codeGram_isCorrelation
#print axioms WeakSimplex.map_codeScore_stdGaussian
#print axioms WeakSimplex.classLikelihood
#print axioms WeakSimplex.classLikelihood_eq_exp_score
#print axioms WeakSimplex.classLikelihoodMax
#print axioms WeakSimplex.bayesValue
#print axioms WeakSimplex.measurable_classLikelihood
#print axioms WeakSimplex.measurable_classLikelihoodMax
#print axioms WeakSimplex.integrable_classLikelihood
#print axioms WeakSimplex.integrable_classLikelihoodMax
#print axioms WeakSimplex.bayesValue_eq_gramMgf
#print axioms WeakSimplex.mlDecoder
#print axioms WeakSimplex.mlDecoder_maximizes
#print axioms WeakSimplex.mlDecoder_le_of_maximizes
#print axioms WeakSimplex.classLikelihood_mlDecoder_eq_max
#print axioms WeakSimplex.measurable_mlDecoder
#print axioms WeakSimplex.IsLikelihoodMaximizingDecoder
#print axioms WeakSimplex.IsScoreMaximizingDecoder
#print axioms WeakSimplex.IsScoreMaximizingDecoder.isLikelihoodMaximizing
#print axioms WeakSimplex.decoderSuccessOf
#print axioms WeakSimplex.decoderSuccess
#print axioms WeakSimplex.decoderSuccessOf_eq_bayesValue
#print axioms WeakSimplex.decoderSuccessOf_eq_of_isLikelihoodMaximizing
#print axioms WeakSimplex.mlDecoder_success_eq_bayesValue
#print axioms WeakSimplex.regularSimplexBayesValue
#print axioms WeakSimplex.bayesValue_eq_regularSimplexBayesValue_of_codeGram
#print axioms WeakSimplex.bayesValue_le_regularSimplex
#print axioms WeakSimplex.bayesValue_lt_regularSimplex
#print axioms WeakSimplex.bayesValue_eq_regularSimplex_iff
#print axioms WeakSimplex.weak_simplex
#print axioms WeakSimplex.weak_simplex_strict
#print axioms WeakSimplex.weak_simplex_eq_iff_codeGram_eq
#print axioms WeakSimplex.weak_simplex_of_scoreMaximizingDecoders
#print axioms WeakSimplex.weak_simplex_strict_of_scoreMaximizingDecoders
#print axioms WeakSimplex.weak_simplex_eq_iff_codeGram_eq_of_scoreMaximizingDecoders
