import WeakSimplexConjectureLean.Basic
import WeakSimplexConjectureLean.Coding.BayesValue
import WeakSimplexConjectureLean.Coding.Gram
import WeakSimplexConjectureLean.Coding.MLDecoder
import WeakSimplexConjectureLean.Coding.Normalization
import WeakSimplexConjectureLean.Coding.RegularSimplex
import WeakSimplexConjectureLean.Coding.WeakSimplex
import WeakSimplexConjectureLean.Core.Correlation
import WeakSimplexConjectureLean.Gaussian.DensityRatio
import WeakSimplexConjectureLean.Gaussian.Regularization
import WeakSimplexConjectureLean.Gaussian.Shift
import WeakSimplexConjectureLean.LogConcavity.Indicators
import WeakSimplexConjectureLean.LogConcavity.Prekopa
import WeakSimplexConjectureLean.Maxima.CoordinateMax
import WeakSimplexConjectureLean.Maxima.StochasticOrder
import WeakSimplexConjectureLean.Maxima.ExponentialMoments
import WeakSimplexConjectureLean.Maxima.StrictStochasticOrder
import WeakSimplexConjectureLean.Maxima.StrictExponentialMoments
import WeakSimplexConjectureLean.Normal.TruncatedMoments
import WeakSimplexConjectureLean.Normal.TiltFunctions
import WeakSimplexConjectureLean.Orthant.AdaptiveReduction
import WeakSimplexConjectureLean.Orthant.PositiveDefiniteConditional
import WeakSimplexConjectureLean.Orthant.PositiveDefinite
import WeakSimplexConjectureLean.Orthant.Singular
import WeakSimplexConjectureLean.Orthant.Strict
import WeakSimplexConjectureLean.Product.CenteredProperty
import WeakSimplexConjectureLean.Product.SymmetricRectangle
import WeakSimplexConjectureLean.Product.EvenLayerCake
import WeakSimplexConjectureLean.Product.NormalizedSelfConvolution
import WeakSimplexConjectureLean.Product.SumDifference
import WeakSimplexConjectureLean.Product.DyadicCLT
import WeakSimplexConjectureLean.Product.PositiveLowerBound
import WeakSimplexConjectureLean.Product.CenteredProduct
import WeakSimplexConjectureLean.Product.ContinuousCenteredProduct
import WeakSimplexConjectureLean.Rigidity.TiltedHalfLineProduct
import WeakSimplexConjectureLean.Tilt.AdaptiveWitnesses
import WeakSimplexConjectureLean.Tilt.CompactMaximizer
import WeakSimplexConjectureLean.Tilt.EventShift
import WeakSimplexConjectureLean.Tilt.NormalizedTiltedHalfLine
import WeakSimplexConjectureLean.Tilt.RankOneInverse
import WeakSimplexConjectureLean.Tilt.SingularWitnesses
import WeakSimplexConjectureLean.Tilt.TiltedHalfLine

/-!
# Weak Simplex Conjecture Lean

Umbrella import for the public formalization of Gaussian stochastic domination and the Weak
Simplex Conjecture.
-/
